"""Attack-type ({tts, vc}) labeling for remediation track 4. See
docs/superpowers/specs/2026-09-11-attack-type-differentiator-design.md §3
for the per-source-directory coverage this implements and the caveat on
the ASVspoof2019 attack-ID table below.

NOTE: the table below is a draft based on the well-established convention
that A05/A06 and A17-A19 are voice-conversion systems in the ASVspoof2019
LA taxonomy, with A13 a TTS+VC hybrid bucketed here as VC (its VC stage is
the final signal-transforming step). It has NOT been independently
verified against the official ASVspoof2019 evaluation plan table — do not
treat this as authoritative without that check; an error here silently
mislabels training examples. A17-A19 are the one part of this table
empirically confirmed (via model_training/test_assets/
voice_conversion_asvspoof_a17.wav actually being generated by a
conversion, not synthesis, process)."""
from __future__ import annotations

from pathlib import Path

ATTACK_ID_TO_TYPE: dict[str, str] = {
    "A01": "tts", "A02": "tts", "A03": "tts", "A04": "tts",
    "A05": "vc", "A06": "vc",
    "A07": "tts", "A08": "tts", "A09": "tts", "A10": "tts",
    "A11": "tts", "A12": "tts",
    "A13": "vc",  # TTS+VC hybrid, bucketed as vc — see module docstring
    "A14": "vc", "A15": "vc",
    "A16": "tts",
    "A17": "vc", "A18": "vc", "A19": "vc",
}

# Directories where every fake file is TTS by construction (verified
# against each source's own generation script docstring — see the design
# spec §3 table). Keyed by resolved absolute path string.
DIRECTORY_DEFAULT_ATTACK_TYPE: dict[str, str] = {}


def register_tts_only_directory(path: Path) -> None:
    """Call once per known-all-TTS directory (MLAAD, XTTS/YourTTS/MMS
    accent-expansion fakes) during corpus setup, so attack_type_for_file
    can resolve it without a per-file map."""
    DIRECTORY_DEFAULT_ATTACK_TYPE[str(Path(path).resolve())] = "tts"


def load_asvspoof_attack_map(protocol_path: Path) -> dict[str, str]:
    """Parses a trial_metadata.txt-format ASVspoof2019/2021 protocol file
    (columns: speaker_id utt_id codec tx attack_id key trim subset) into
    {utt_id: "tts"|"vc"}. Bonafide rows (key == "bonafide", attack_id "-")
    carry no attack type and are omitted, not mapped to a placeholder."""
    result: dict[str, str] = {}
    with open(protocol_path) as f:
        for line in f:
            parts = line.split()
            if len(parts) < 6:
                continue
            utt_id, attack_id, key = parts[1], parts[4], parts[5]
            if key != "spoof" or attack_id not in ATTACK_ID_TO_TYPE:
                continue
            result[utt_id] = ATTACK_ID_TO_TYPE[attack_id]
    return result


def load_asvspoof_2019_train_attack_map(protocol_path: Path) -> dict[str, str]:
    """Parses the ASVspoof2019 LA train protocol format (columns:
    speaker_id utt_id - attack_id key — no codec/tx/trim/subset columns,
    unlike the 2021 trial_metadata.txt format load_asvspoof_attack_map
    handles) into {utt_id: "tts"|"vc"}."""
    result: dict[str, str] = {}
    with open(protocol_path) as f:
        for line in f:
            parts = line.split()
            if len(parts) < 5:
                continue
            utt_id, attack_id, key = parts[1], parts[3], parts[4]
            if key != "spoof" or attack_id not in ATTACK_ID_TO_TYPE:
                continue
            result[utt_id] = ATTACK_ID_TO_TYPE[attack_id]
    return result


def attack_type_for_file(
    wav_path: Path, source_dir: str, per_file_map: dict[str, str] | None
) -> str:
    """Resolves one file's attack type: per-file map first (e.g.
    ASVspoof2021's trial_metadata.txt, keyed by filename stem), then the
    directory-level default (e.g. MLAAD, accent-expansion TTS dirs),
    else "unknown" (In-the-Wild, CodecFake — no ground truth available)."""
    if per_file_map is not None:
        stem = wav_path.stem
        if stem in per_file_map:
            return per_file_map[stem]
    resolved_dir = str(Path(source_dir).resolve())
    return DIRECTORY_DEFAULT_ATTACK_TYPE.get(resolved_dir, "unknown")
